### ISSUE TITLE
Lora text extractor bug

### ISSUE THREAD

**Issue by featherice** [skfoo/ComfyUI-Coziness#1]
Basically it is unusable with negative weight. Input loraname:-0.5:-0.8 becomes loraname:0.5:0.8

**Comment by skfoo** [comment]
Thanks for the report, but I haven't been able to reproduce this. For example, here's two pizzas with -2/+2 add_detail,

![low detail](https://github.com/skfoo/ComfyUI-Coziness/assets/44075232/7fa956dd-51ea-4d60-aad6-308e9cc96a65)
![high detail](https://github.com/skfoo/ComfyUI-Coziness/assets/44075232/5b964df1-a0c6-43fe-bc8d-4022b9e9b275)

**Comment by featherice** [comment]
Ok, i fiddled with it a little bit more and found out why it was a bit confusing..
"\<lora:more_details:-0.5:0.5>, " when put through lora extractor becomes "\<lora:more_details:-0.5:0.5>", but if instead i just start with "more_details-0.5:0.5, " it becomes filtered out entirely, i checked it with Show Text node. I assumed that loraname:1.0:1.0 syntax is ok, but it must be \<lora:loraname:1.0:1.0>.

**Comment by skfoo** [comment]
Yeah, I guess I didn't specifically say that, but it looks for Automatic's "extra networks" syntax, which is like `<network-name:parameters...>`, where 'network-name' is 'lora' if the prompt is specifying a lora to load. So I scan the prompt for any lora commands (things like `<lora:...>`) and send those to the Extracted Text output. Everything else stays in the prompt.
