### ISSUE TITLE
Plz make "MultiLora Loader" no running again when fixed the seed num

### ISSUE THREAD

**Issue by xueqing0622** [skfoo/ComfyUI-Coziness#4]
Plz make "MultiLora Loader" no running again when fixed the seed num
when fixed the seed num,  "MultiLora Loader"  also running everytime, it make workflow no perfect, plz fixed it, 

thx, have a nice day

**Comment by skfoo** [comment]
ComfyUI decides itself if a node needs to run again, so this node should only be run again if its inputs were changed.

**Comment by xueqing0622** [comment]
even the nothing change, the prompt only "1girl", the fixed seed, it still run again

**Comment by skfoo** [comment]
I'm going to close this; I kept it open to see if anyone else had anything to say but I don't think there's anything I can do. I tried doing my own test with a fixed seed, when I hit 'queue prompt' again ComfyUI doesn't do anything because nothing changed :/

**Comment by xueqing0622** [comment]
ok, still thank!  I asked Dr.Lt.Data to do all in ImpactWildcardEncode 
https://githubfast.com/ltdrdata/ComfyUI-Impact-Pack/issues/201#issuecomment-1751933968
https://githubfast.com/ltdrdata/ComfyUI-Impact-Pack/issues/219#issuecomment-1759294067
